# Generated by Django 3.1.3 on 2020-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to='outputs/'),
        ),
    ]
