# Generated by Django 3.1.3 on 2021-01-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project0', '0006_auto_20210117_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='img_h',
        ),
        migrations.RemoveField(
            model_name='word',
            name='img_w',
        ),
    ]
