# Generated by Django 3.1.3 on 2021-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project0', '0007_auto_20210125_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_bg_w',
            field=models.BooleanField(default=True),
        ),
    ]
